### PR TITLE
Add leiningen project file for leiningen toolchains.

### PR DESCRIPTION
**Pull request by whilo**
I really like your work with FFTs and overtone as I am interested in learning more about FFT and find the combination of overtone life-synthesis and visualization of code really appealing. It took me some time to find this development branch for your blog post, since the master branch doesn't have the code to the blog post in it. I have added a leiningen file to make it easy to experiment, but now it seems I have hit a bug within the JVM/JFrame implementation. http://paste.ubuntu.com/6762781/ I don't have the time right now, but if you need more information, ping me. I might have look into it in the future.

### CODE REVIEW

**Comment by mikera** [comment]
Looks good, thanks!

As far as the bug goes I have no idea.... looks like an X Windows issue with the OpenJDK?

**Comment by whilo** [comment]
Thx for merging. Could you link the code from the blog posting/merge the devel-branch as well? At the moment the blog post points to your master branch, which does not have the code in it.

**Comment by mikera** [comment]
I changed develop to be the default branch, this should fix the problem :-)

**Comment by whilo** [comment]
Ok, again thanks for your awesome work!

**Pull request merged**
